version: '3'

services:
  db:
    restart: always
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  web:
    restart: always
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             ./entrypoint.sh &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_HOST: db
    depends_on:
      - db